---
- name: Import AAP
  hosts: 192.168.1.10
  collections:
    - awx.awx
  tasks:
  
  - name: Export all assets
    export:
      all: True
    register: export_output

  - name: Import all assets from our export
    import:
      assets: "{{ export_output.assets }}"

  - name: Load data from a json file created by a command like awx export --organization Default
    import:
      assets: "{{ lookup('file', 'org.json') | from_json() }}"
