---
- name: Import AAP
  hosts: 192.168.1.10
  vars:
      ansible_python_interpreter: /usr/bin/python3.9
  tasks:

  - name: Export all assets
    awx.awx.export:
        controller_host: 192.168.1.10
        controller_username: admin
        controller_password: admin123
        all: True
    register: export_output

  - name: Import all assets from our export
    awx.awx.import:
        assets: "{{ export_output.assets }}"

  - name: Load data from a json file created by a command like awx export --organization Default
    awx.awx.import:
        assets: "{{ lookup('file', 'org.json') | from_json() }}"
